### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by tristanz** [cryptix/exp#1]
I'm playing around with GraphQL and like your parser implementation.  Any chance you'd put an explicit license on this code?  Ideally MIT or BSD?

**Comment by cryptix** [comment]
Hey @tristanz, sorry for the long delay. I guess you whipped up your own parser by now? If not, I'm tempted to move this out into it's own repo now that the draft specs are out.

**Comment by tristanz** [comment]
I've played around with it, but haven't done anything real.  It would be awesome to break this out and start work on a real gographql repository that is spec compatible.  This will obviously happen one way or another but currently you have a head start.

**Comment by cryptix** [comment]
Hey @tristanz, I moved the code to this repo: https://github.com/cryptix/go-graphql.

I'm open to any and every feedback you might have :)

(ps. it's MIT licensed)
