### ISSUE TITLE
Official GraphQL spec

### ISSUE THREAD

**Issue by F21** [cryptix/exp#2]
I know this repo is just an experimental repo, but the official GraphQL spec (https://github.com/facebook/graphql) is now out. It's still an early draft, but should help guide your implementation.

**Comment by cryptix** [comment]
Oh, nice! Honestly I nearly forgot about this while I waited for more specs. Thanks for the reminder! :)

**Comment by cryptix** [comment]
Btw: I moved the graphql package to it's own repo here: https://github.com/cryptix/go-graphql
